unit DriverCommands;

interface
uses
  BinUtils;

function GetCommandName(Command: AnsiString): string; overload;
function GetCommandName(Command: Word): string; overload;

implementation

const
  SCommandName01 = 'Запрос дампа';
  SCommandName02 = 'Запрос данных';
  SCommandName03 = 'Прерывание выдачи данных';
  SCommandName0D = 'Фискализация с длинным РНМ';
  SCommandName0E = 'Ввод длинного заводского номера';
  SCommandName0F = 'Запрос длинного заводского номера';
  SCommandName10 = 'Короткий запрос состояния';
  SCommandName11 = 'Запрос состояния';
  SCommandName12 = 'Печать жирной строки';
  SCommandName13 = 'Гудок';
  SCommandName14 = 'Установка параметров обмена';
  SCommandName15 = 'Чтение параметров обмена';
  SCommandName16 = 'Технологическое обнуление';
  SCommandName17 = 'Печать строки';
  SCommandName18 = 'Печать заголовка документа';
  SCommandName19 = 'Тестовый прогон';
  SCommandName1A = 'Запрос денежного регистра';
  SCommandName1B = 'Запрос операционного регистра';
  SCommandName1C = 'Запись лицензии';
  SCommandName1D = 'Чтение лицензии';
  SCommandName1E = 'Запись таблицы';
  SCommandName1F = 'Чтение таблицы';
  SCommandName20 = 'Запись положения десятичной точки';
  SCommandName21 = 'Программирование времени';
  SCommandName22 = 'Программирование даты';
  SCommandName23 = 'Подтверждение программирования даты';
  SCommandName24 = 'Инициализация таблиц';
  SCommandName25 = 'Отрезка чека';
  SCommandName26 = 'Прочитать параметры шрифта';
  SCommandName27 = 'Общее гашение';
  SCommandName28 = 'Открыть денежный ящик';
  SCommandName29 = 'Протяжка';
  SCommandName2A = 'Выброс подкладного документа';
  SCommandName2B = 'Прерывание тестового прогона';
  SCommandName2C = 'Снятие показаний операционных регистров';
  SCommandName2D = 'Запрос структуры таблицы';
  SCommandName2E = 'Запрос структуры поля';
  SCommandName2F = 'Печать строки данным шрифтом';
  SCommandName40 = 'Суточный отчет без гашения';
  SCommandName41 = 'Суточный отчет с гашением';
  SCommandName42 = 'Отчёт по секциям';
  SCommandName43 = 'Отчёт по налогам';
  SCommandName44 = 'Отчёт по кассирам'; { !!! }
  SCommandName45 = 'Отчёт почасовой'; { !!! }
  SCommandName46 = 'Отчёт по товарам'; { !!! }
  SCommandName4E = 'Загрузка графики 512'; { !!! }
  SCommandName4F = 'Печать графики с масштабированием'; { !!! }
  SCommandName50 = 'Внесение';
  SCommandName51 = 'Выплата';
  SCommandName52 = 'Печать клише'; { !!! }
  SCommandName53 = 'Завершение документа и печать клише'; { !!! }
  SCommandName54 = 'Печать рекламного текста'; { !!! }
  SCommandName57 = 'Закрытие чека (Беларусь)';
  SCommandName60 = 'Ввод заводского номера';
  SCommandName61 = 'Инициализация ФП';
  SCommandName62 = 'Запрос суммы записей в ФП';
  SCommandName63 = 'Запрос даты последней записи в ФП';
  SCommandName64 = 'Запрос диапазона дат и смен';
  SCommandName65 = 'Фискализация';
  SCommandName66 = 'Фискальный отчет по диапазону дат';
  SCommandName67 = 'Фискальный отчет по диапазону смен';
  SCommandName68 = 'Прерывание полного отчета';
  SCommandName69 = 'Чтение параметров фискализации';
  SCommandName6B = 'Запрос описания ошибки';
  SCommandName70 = 'Открыть фискальный подкладной документ';
  SCommandName71 = 'Открыть стандартный фискальный подкладной документ';
  SCommandName72 = 'Формирование операции на подкладном документе';
  SCommandName73 = 'Формирование стандартной операции на подкладном документе';
  SCommandName74 = 'Формирование скидки на подкладном документе';
  SCommandName75 = 'Формирование стандартной скидки на подкладном документе';
  SCommandName76 = 'Формирование закрытия чека на подкладном документе';
  SCommandName77 = 'Формирование стандартного закрытия чека на подкладном документе';
  SCommandName78 = 'Конфигурация подкладного документа';
  SCommandName79 = 'Установка стандартной конфигурации подкладного документа';
  SCommandName7A = 'Заполнение буфера подкладного документа нефискальной информацией';
  SCommandName7B = 'Очистка строки буфера подкладного документа от нефискальной информации';
  SCommandName7C = 'Очистка всего буфера подкладного документа от нефискальной информации';
  SCommandName7D = 'Печать подкладного документа';
  SCommandName7E = 'Общая конфигурация подкладного документа';
  SCommandName80 = 'Продажа';
  SCommandName81 = 'Покупка';
  SCommandName82 = 'Возврат продажи';
  SCommandName83 = 'Возврат покупки';
  SCommandName84 = 'Сторно';
  SCommandName85 = 'Закрытие чека';
  SCommandName86 = 'Скидка';
  SCommandName87 = 'Надбавка';
  SCommandName88 = 'Аннулирование чека';
  SCommandName89 = 'Подытог чека';
  SCommandName8A = 'Сторно скидки';
  SCommandName8B = 'Сторно надбавки';
  SCommandName8C = 'Повтор документа';
  SCommandName8D = 'Открыть чек';
  SCommandName90 = 'Формирование чека отпуска нефтепродуктов в режиме предоплаты заданной дозы';
  SCommandName91 = 'Формирование чека отпуска нефтепродуктов в режиме предоплаты на заданную сумму';
  SCommandName92 = 'Формирование чека коррекции при неполном отпуске нефтепродуктов';
  SCommandName93 = 'Задание дозы РК в миллилитрах';
  SCommandName94 = 'Задание дозы РК в денежных единицах';
  SCommandName95 = 'Продажа нефтепродуктов';
  SCommandName96 = 'Останов РК';
  SCommandName97 = 'Пуск РК';
  SCommandName98 = 'Сброс РК';
  SCommandName99 = 'Сброс всех ТРК';
  SCommandName9A = 'Задание параметров РК';
  SCommandName9B = 'Считать литровый суммарный счетчик';
  SCommandName9E = 'Запрос текущей дозы РК';
  SCommandName9F = 'Запрос состояния РК';
  SCommandNameA0 = 'Отчет ЭКЛЗ по отделам в заданном диапазоне дат';
  SCommandNameA1 = 'Отчет ЭКЛЗ по отделам в заданном диапазоне номеров смен';
  SCommandNameA2 = 'Отчет ЭКЛЗ по закрытиям смен в заданном диапазоне дат';
  SCommandNameA3 = 'Отчет ЭКЛЗ по закрытиям смен в заданном диапазоне номеров смен';
  SCommandNameA4 = 'Итоги смены по номеру смены ЭКЛЗ';
  SCommandNameA5 = 'Платежный документ из ЭКЛЗ по номеру КПК';
  SCommandNameA6 = 'Контрольная лента из ЭКЛЗ по номеру смены';
  SCommandNameA7 = 'Прерывание полного отчета ЭКЛЗ';
  SCommandNameA8 = 'Итог активизации ЭКЛЗ';
  SCommandNameA9 = 'Активизация ЭКЛЗ';
  SCommandNameAA = 'Закрытие архива ЭКЛЗ';
  SCommandNameAB = 'Запрос регистрационного номера ЭКЛЗ';
  SCommandNameAC = 'Прекращение ЭКЛЗ';
  SCommandNameAD = 'Запрос состояния ЭКЛЗ по коду 1';
  SCommandNameAE = 'Запрос состояния ЭКЛЗ по коду 2';
  SCommandNameAF = 'Тест целостности архива ЭКЛЗ';
  SCommandNameB0 = 'Продолжение печати';
  SCommandNameB1 = 'Запрос версии ЭКЛЗ';
  SCommandNameB2 = 'Инициализация архива ЭКЛЗ';
  SCommandNameB3 = 'Запрос данных отчёта ЭКЛЗ';
  SCommandNameB4 = 'Запрос контрольной ленты ЭКЛЗ';
  SCommandNameB5 = 'Запрос документа ЭКЛЗ';
  SCommandNameB6 = 'Запрос отчёта ЭКЛЗ по отделам в заданном диапазоне дат';
  SCommandNameB7 = 'Запрос отчёта ЭКЛЗ по отделам в заданном диапазоне номеров смен';
  SCommandNameB8 = 'Запрос отчёта ЭКЛЗ по закрытиям смен в заданном диапазоне дат';
  SCommandNameB9 = 'Запрос отчёта ЭКЛЗ по закрытиям смен в заданном диапазоне номеров смен';
  SCommandNameBA = 'Запрос в ЭКЛЗ итогов смены по номеру смены';
  SCommandNameBB = 'Запрос итога активизации ЭКЛЗ';
  SCommandNameBC = 'Вернуть ошибку ЭКЛЗ';
  SCommandNameC0 = 'Загрузка графики';
  SCommandNameC1 = 'Печать графики';
  SCommandNameC2 = 'Печать штрихкода';
  SCommandNameC3 = 'Печать расширенной графики';
  SCommandNameC4 = 'Загрузка расширенной графики';
  SCommandNameC5 = 'Печать графической линии'; { !!! }
  SCommandNameD0 = 'Запрос состояния принтера IBM';
  SCommandNameD1 = 'Краткий запрос состояния принтера IBM';
  SCommandNameE0 = 'Открытие смены';
  SCommandNameF0 = 'Управление заслонкой';
  SCommandNameF1 = 'Выдать чек';
  SCommandNameFC = 'Получить тип устройства';
  SCommandNameFD = 'Управление портом';
  SCommandNameFE = 'Сервисная команда';

  SCommandNameFE03 = 'Загрузка символа шрифта'; { !!! }
  SCommandNameFE05 = 'Включение простого режима обмена';
  SCommandNameFE06 = 'Выключение простого режима обмена';
  SCommandNameFEE6 = 'Запись лицензий функционала';
  SCommandNameFEE7 = 'Чтение лицензий функционала';
  SCommandNameFEEC = 'Чтение версии загрузчика';
  SCommandNameFEED = 'Переход в режим DFU';
  SCommandNameFEF1 = 'Повторный ввод заводского номера';
  SCommandNameFEF2 = 'Пинг';
  SCommandNameFEF3 = 'Перезагрузка ККТ';
  SCommandNameFEF4 = 'Запрос необнуляемых сумм';
  SCommandNameFEF5 = 'Ввод заводского номера';
  SCommandNameFEEE = 'Запись лицензий ККТ';
  SCommandNameFEEF = 'Чтение лицензий ККТ';







  SCommandNameF7 = 'Запрос параметров модели';

  SCommandNameFF01 = 'Запрос статуса ФН';
  SCommandNameFF02 = 'Запрос номера ФН'; // FF02H	3
  SCommandNameFF03 = 'Запрос срока действия ФН'; // FF03H	3
  SCommandNameFF04 = 'Запрос версии ФН'; // FF04H	4
  SCommandNameFF05 = 'Начать отчет о регистрации ККТ'; // FF05H	4
  SCommandNameFF06 = 'Сформировать отчёт о регистрации ККТ'; // FF06H	4
  SCommandNameFF07 = 'Сброс состояния ФН'; // FF07H	4
  SCommandNameFF08 = 'Отменить документ в ФН'; // FF08H	5
  SCommandNameFF09 = 'Запрос итогов последней фискализации (перерегистрации)'; // FF09H	5
  SCommandNameFF0A = 'Найти фискальный документ по номеру'; // FF0AH	6
  SCommandNameFF0B = 'Открыть смену в ФН'; // FF0BH	6
  SCommandNameFF0C = 'Передать произвольную TLV структуру'; // FF0CH	6
  SCommandNameFF0D = 'Операция со скидками и надбавками'; // FF0DH	6
  SCommandNameFF30 = 'Запросить о наличие данных в буфере'; // FF30H	7
  SCommandNameFF31 = 'Прочитать блок данных из буфера'; // FF31H	7
  SCommandNameFF32 = 'Начать запись данных в буфер'; // FF32H	8
  SCommandNameFF33 = 'Записать блок данных в буфер'; // FF33H	8
  SCommandNameFF34 = 'Сформировать отчёт о перерегистрации ККТ'; // FF34H	8
  SCommandNameFF35 = 'Начать формирование чека коррекции'; // FF35H	8
  SCommandNameFF36 = 'Сформировать чек коррекции'; // FF36H	8
  SCommandNameFF37 = 'Начать формирование отчёта о состоянии расчётов'; // FF37H	9
  SCommandNameFF38 = 'Сформировать отчёт о состоянии расчётов'; // FF38H	9
  SCommandNameFF39 = 'Получить статус информационного  обмена'; // FF39H	9
  SCommandNameFF3A = 'Запросить фискальный документ в TLV формате'; // FF3AH	10
  SCommandNameFF3B = 'Чтение TLV фискального документа'; // FF3BH	10
  SCommandNameFF3C = 'Запрос квитанции о получении данных в ОФД по номеру  документа'; // FF3CH	10
  SCommandNameFF3D = 'Начать закрытие фискального режима'; // FF3DH	10
  SCommandNameFF3E = 'Закрыть фискальный режим'; // FF3EH	10
  SCommandNameFF3F = 'Запрос количества ФД на которые нет квитанции'; // FF3FH	11
  SCommandNameFF40 = 'Запрос параметров текущей смены'; // FF40H	11
  SCommandNameFF41 = 'Начать открытие смены'; // FF41H	11
  SCommandNameFF42 = 'Начать закрытие смены'; // FF42H	11
  SCommandNameFF43 = 'Закрыть смену в ФН'; // FF43H	11
  SCommandNameFF45 = 'Закрытие чека расширенное вариант V2'; // FF45H	12
  SCommandNameFF46 = 'Операция V2'; // FF46H	13
  SCommandNameFF47 = 'Дополнительный реквизит ФНС'; // FF47H	14
  SCommandNameFF48 = 'Скидки и надбавки в операции'; // FF48H	14
  SCommandNameFF49 = 'Передача кода товарной номенклатуры'; // FF49H	14
  SCommandNameFF4A = 'Сформировать чек коррекции V2'; // FF4AH	14
  SCommandNameFF4B = 'Скидка, надбавка на чек для Роснефти'; // FF4BH	15
  SCommandNameFF4C = 'Запрос итогов фискализации (перерегистрации) V2'; // FF4CH	15
  SCommandNameFF4D = 'Передать произвольную TLV структуру привязанную к операции'; // FF4DH.	16
  SCommandNameFF4E = 'Запись блока данных прошивки  ФР на SD карту'; // FF4EH	16
  SCommandNameFF50 = 'Онлайн платёж'; // FF50H	16
  SCommandNameFF51 = 'Статус онлайн платёжа'; // FF51H	17
  SCommandNameFF52 = 'Получить реквизит последнего онлайн платёжа'; // FF52H	17
  SCommandNameFF60 = 'Запрос параметра фискализации '; // FF60H	17
  SCommandNameFF61 = 'Проверка  маркированного товара'; // FF61H	18
  SCommandNameFF62 = 'Синхронизировать регистры со счётчиком ФН'; // FF62H	18
  SCommandNameFF63 = 'Запрос ресурса свободной памяти  в ФН'; // FF63H	18
  SCommandNameFF64 = 'Передача в ФН  TLV из буфера'; // FF64H	19
  SCommandNameFF65 = 'Получить случайную последовательность'; // FF65H
  SCommandNameFF66 = 'Авторизация'; // FF66H
  SCommandNameFF67 = 'Привязка  маркированного товара к позиции'; // FF67H
  SCommandNameFF68 = 'Получить состояние по передачи уведомлений'; // FF68H
  SCommandNameFF69 = 'Принять/отклонить КМ'; // FF69H
  SCommandNameFF70 = 'Запрос статуса по работе с кодами маркировки'; // FF70H
  SCommandNameFF71 = 'Начать выгрузку уведомлений  о реализации маркированных товаров'; // FF71H
  SCommandNameFF72 = 'Прочитать блок уведомления'; // FF72H
  SCommandNameFF73 = 'Подтвердить выгрузку уведомления'; // FF73H
  SCommandNameFF74 = 'Запрос исполнения ФН'; // FF74H
  SCommandNameFF75 = 'Запрос размера данных документа в ФН'; // FF73H

function GetCommandName(Command: Word): string; overload;
var
  Res: PResStringRec;
begin
  case Command of
    $01: Result := SCommandName01;
    $02: Result := SCommandName02;
    $03: Result := SCommandName03;
    $0D: Result := SCommandName0D;
    $0E: Result := SCommandName0E;
    $0F: Result := SCommandName0F;
    $10: Result := SCommandName10;
    $11: Result := SCommandName11;
    $12: Result := SCommandName12;
    $13: Result := SCommandName13;
    $14: Result := SCommandName14;
    $15: Result := SCommandName15;
    $16: Result := SCommandName16;
    $17: Result := SCommandName17;
    $18: Result := SCommandName18;
    $19: Result := SCommandName19;
    $1A: Result := SCommandName1A;
    $1B: Result := SCommandName1B;
    $1C: Result := SCommandName1C;
    $1D: Result := SCommandName1D;
    $1E: Result := SCommandName1E;
    $1F: Result := SCommandName1F;
    $20: Result := SCommandName20;
    $21: Result := SCommandName21;
    $22: Result := SCommandName22;
    $23: Result := SCommandName23;
    $24: Result := SCommandName24;
    $25: Result := SCommandName25;
    $26: Result := SCommandName26;
    $27: Result := SCommandName27;
    $28: Result := SCommandName28;
    $29: Result := SCommandName29;
    $2A: Result := SCommandName2A;
    $2B: Result := SCommandName2B;
    $2C: Result := SCommandName2C;
    $2D: Result := SCommandName2D;
    $2E: Result := SCommandName2E;
    $2F: Result := SCommandName2F;
    $40: Result := SCommandName40;
    $41: Result := SCommandName41;
    $42: Result := SCommandName42;
    $43: Result := SCommandName43;
    $4E: Result := SCommandName4E;
    $4F: Result := SCommandName4F;
    $50: Result := SCommandName50;
    $51: Result := SCommandName51;
    $52: Result := SCommandName52;
    $53: Result := SCommandName53;
    $54: Result := SCommandName54;
    $57: Result := SCommandname57;
    $60: Result := SCommandName60;
    $61: Result := SCommandName61;
    $62: Result := SCommandName62;
    $63: Result := SCommandName63;
    $64: Result := SCommandName64;
    $65: Result := SCommandName65;
    $66: Result := SCommandName66;
    $67: Result := SCommandName67;
    $68: Result := SCommandName68;
    $69: Result := SCommandName69;
    $6B: Result := SCommandName6B;
    $70: Result := SCommandName70;
    $71: Result := SCommandName71;
    $72: Result := SCommandName72;
    $73: Result := SCommandName73;
    $74: Result := SCommandName74;
    $75: Result := SCommandName75;
    $76: Result := SCommandName76;
    $77: Result := SCommandName77;
    $78: Result := SCommandName78;
    $79: Result := SCommandName79;
    $7A: Result := SCommandName7A;
    $7B: Result := SCommandName7B;
    $7C: Result := SCommandName7C;
    $7D: Result := SCommandName7D;
    $7E: Result := SCommandName7E;
    $80: Result := SCommandName80;
    $81: Result := SCommandName81;
    $82: Result := SCommandName82;
    $83: Result := SCommandName83;
    $84: Result := SCommandName84;
    $85: Result := SCommandName85;
    $86: Result := SCommandName86;
    $87: Result := SCommandName87;
    $88: Result := SCommandName88;
    $89: Result := SCommandName89;
    $8A: Result := SCommandName8A;
    $8B: Result := SCommandName8B;
    $8C: Result := SCommandName8C;
    $8D: Result := SCommandName8D;
    $90: Result := SCommandName90;
    $91: Result := SCommandName91;
    $92: Result := SCommandName92;
    $93: Result := SCommandName93;
    $94: Result := SCommandName94;
    $95: Result := SCommandName95;
    $96: Result := SCommandName96;
    $97: Result := SCommandName97;
    $98: Result := SCommandName98;
    $99: Result := SCommandName99;
    $9A: Result := SCommandName9A;
    $9B: Result := SCommandName9B;
    $9E: Result := SCommandName9E;
    $9F: Result := SCommandName9F;
    $A0: Result := SCommandNameA0;
    $A1: Result := SCommandNameA1;
    $A2: Result := SCommandNameA2;
    $A3: Result := SCommandNameA3;
    $A4: Result := SCommandNameA4;
    $A5: Result := SCommandNameA5;
    $A6: Result := SCommandNameA6;
    $A7: Result := SCommandNameA7;
    $A8: Result := SCommandNameA8;
    $A9: Result := SCommandNameA9;
    $AA: Result := SCommandNameAA;
    $AB: Result := SCommandNameAB;
    $AC: Result := SCommandNameAC;
    $AD: Result := SCommandNameAD;
    $AE: Result := SCommandNameAE;
    $AF: Result := SCommandNameAF;
    $B0: Result := SCommandNameB0;
    $B1: Result := SCommandNameB1;
    $B2: Result := SCommandNameB2;
    $B3: Result := SCommandNameB3;
    $B4: Result := SCommandNameB4;
    $B5: Result := SCommandNameB5;
    $B6: Result := SCommandNameB6;
    $B7: Result := SCommandNameB7;
    $B8: Result := SCommandNameB8;
    $B9: Result := SCommandNameB9;
    $BA: Result := SCommandNameBA;
    $BB: Result := SCommandNameBB;
    $BC: Result := SCommandNameBC;
    $C0: Result := SCommandNameC0;
    $C1: Result := SCommandNameC1;
    $C2: Result := SCommandNameC2;
    $C3: Result := SCommandNameC3;
    $C4: Result := SCommandNameC4;
    $C5: Result := SCommandNameC5;
    $D0: Result := SCommandNameD0;
    $D1: Result := SCommandNameD1;
    $E0: Result := SCommandNameE0;
    $F0: Result := SCommandNameF0;
    $F1: Result := SCommandNameF1;
    $F7: Result := SCommandNameF7;
    $FC: Result := SCommandNameFC;
    $FD: Result := SCommandNameFD;
    $FE: Result := SCommandNameFE; { !!! }

    $FE03: Result := SCommandNameFE03;
    $FE05: Result := SCommandNameFE05;
    $FE06: Result := SCommandNameFE06;
    $FEE6: Result := SCommandNameFEE6;
    $FEE7: Result := SCommandNameFEE7;
    $FEEC: Result := SCommandNameFEEC;
    $FEED: Result := SCommandNameFEED;
    $FEF1: Result := SCommandNameFEF1;
    $FEF2: Result := SCommandNameFEF2;
    $FEF3: Result := SCommandNameFEF3;
    $FEF4: Result := SCommandNameFEF4;
    $FEF5: Result := SCommandNameFEF5;
    $FEEE: Result := SCommandNameFEEE;
    $FEEF: Result := SCommandNameFEEF;



    $FF01: Result := SCommandNameFF01;
    $FF02: Result := SCommandNameFF02;
    $FF03: Result := SCommandNameFF03;
    $FF04: Result := SCommandNameFF04;
    $FF05: Result := SCommandNameFF05;
    $FF06: Result := SCommandNameFF06;
    $FF07: Result := SCommandNameFF07;
    $FF08: Result := SCommandNameFF08;
    $FF09: Result := SCommandNameFF09;
    $FF0A: Result := SCommandNameFF0A;
    $FF0B: Result := SCommandNameFF0B;
    $FF0C: Result := SCommandNameFF0C;
    $FF0D: Result := SCommandNameFF0D;
    $FF30: Result := SCommandNameFF30;
    $FF31: Result := SCommandNameFF31;
    $FF32: Result := SCommandNameFF32;
    $FF33: Result := SCommandNameFF33;
    $FF34: Result := SCommandNameFF34;
    $FF35: Result := SCommandNameFF35;
    $FF36: Result := SCommandNameFF36;
    $FF37: Result := SCommandNameFF37;
    $FF38: Result := SCommandNameFF38;
    $FF39: Result := SCommandNameFF39;
    $FF3A: Result := SCommandNameFF3A;
    $FF3B: Result := SCommandNameFF3B;
    $FF3C: Result := SCommandNameFF3C;
    $FF3D: Result := SCommandNameFF3D;
    $FF3E: Result := SCommandNameFF3E;
    $FF3F: Result := SCommandNameFF3F;
    $FF40: Result := SCommandNameFF40;
    $FF41: Result := SCommandNameFF41;
    $FF42: Result := SCommandNameFF42;
    $FF43: Result := SCommandNameFF43;
    $FF45: Result := SCommandNameFF45;
    $FF46: Result := SCommandNameFF46;
    $FF47: Result := SCommandNameFF47;
    $FF48: Result := SCommandNameFF48;
    $FF49: Result := SCommandNameFF49;
    $FF4A: Result := SCommandNameFF4A;
    $FF4B: Result := SCommandNameFF4B;
    $FF4C: Result := SCommandNameFF4C;
    $FF4D: Result := SCommandNameFF4D;
    $FF4E: Result := SCommandNameFF4E;
    $FF50: Result := SCommandNameFF50;
    $FF51: Result := SCommandNameFF51;
    $FF52: Result := SCommandNameFF52;
    $FF60: Result := SCommandNameFF60;
    $FF61: Result := SCommandNameFF61;
    $FF62: Result := SCommandNameFF62;
    $FF63: Result := SCommandNameFF63;
    $FF64: Result := SCommandNameFF64;
    $FF65: Result := SCommandNameFF65;
    $FF66: Result := SCommandNameFF66;
    $FF67: Result := SCommandNameFF67;
    $FF68: Result := SCommandNameFF68;
    $FF69: Result := SCommandNameFF69;
    $FF70: Result := SCommandNameFF70;
    $FF71: Result := SCommandNameFF71;
    $FF72: Result := SCommandNameFF72;
    $FF73: Result := SCommandNameFF73;
    $FF74: Result := SCommandNameFF74;
    $FF75: Result := SCommandNameFF75;
  else
    Result := 'Неизвестная команда';
  end;
end;

function GetCommandName(Command: AnsiString): string; overload;
var
  Cmd: Word;
begin
  Cmd := BinToInt(HexToStr(Command), 1, 1);
  if (Cmd = $FF) or (Cmd = $FE) then
    Cmd := (Cmd shl 8) or (BinToInt(HexToStr(Command), 2, 1));
  Result := GetCommandName(Cmd);
end;


end.
