program LogPlayerTst;
uses
  Forms,
  TestFramework,
  GUITestRunner,
  untLogPlayer in '..\..\src\LogPlayer\Unit\untLogPlayer.pas',
  DrvFRLib_TLB in '..\..\src\LogPlayer\Unit\DrvFRLib_TLB.pas',
  untCommand in '..\..\src\LogPlayer\Unit\untCommand.pas',
  DriverCommands in '..\..\src\LogPlayer\Unit\DriverCommands.pas',
  BinUtils in '..\..\src\LogPlayer\Unit\BinUtils.pas',
  NotifyThread in '..\..\src\LogPlayer\Unit\NotifyThread.pas',
  VersionInfo in '..\..\src\LogPlayer\Unit\VersionInfo.pas',
  CommandParser in '..\..\src\LogPlayer\Unit\CommandParser.pas',
  Fp.PrinterTypes in '..\..\src\LogPlayer\Unit\Fp.PrinterTypes.pas',
  Utils.BinStream in '..\..\src\LogPlayer\Unit\Utils.BinStream.pas',
  TLVTags in '..\..\src\LogPlayer\Unit\TLVTags.pas',
  untUtils in '..\..\src\LogPlayer\Unit\untUtils.pas',
  FormatTLV in '..\..\src\LogPlayer\Unit\FormatTLV.pas',
  TLVParser in '..\..\src\LogPlayer\Unit\TLVParser.pas',
  ParserCommandFF46 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF46.pas',
  ParserCommandFF0C in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF0C.pas',
  ParserCommand17 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand17.pas',
  ParserCommand2F in '..\..\src\LogPlayer\Unit\Commands\ParserCommand2F.pas',
  ParserCommand11 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand11.pas',
  PrinterTypes in '..\..\src\LogPlayer\Unit\PrinterTypes.pas',
  DriverTypes in '..\..\src\LogPlayer\Unit\DriverTypes.pas',
  GlobalConst in '..\..\src\LogPlayer\Unit\GlobalConst.pas',
  TextEncoding in '..\..\src\LogPlayer\Unit\TextEncoding.pas',
  LangUtils in '..\..\src\LogPlayer\Unit\LangUtils.pas',
  FileUtils in '..\..\src\LogPlayer\Unit\FileUtils.pas',
  LogFile in '..\..\src\LogPlayer\Unit\LogFile.pas',
  untFileUtil in '..\..\src\LogPlayer\Unit\untFileUtil.pas',
  ParserCommand10 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand10.pas',
  ParserCommandFE in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFE.pas',
  ParserCommand8D in '..\..\src\LogPlayer\Unit\Commands\ParserCommand8D.pas',
  ParserCommand1E in '..\..\src\LogPlayer\Unit\Commands\ParserCommand1E.pas',
  ParserCommand1F in '..\..\src\LogPlayer\Unit\Commands\ParserCommand1F.pas',
  ParserCommand2D in '..\..\src\LogPlayer\Unit\Commands\ParserCommand2D.pas',
  ParserCommand2E in '..\..\src\LogPlayer\Unit\Commands\ParserCommand2E.pas',
  ParserCommand6B in '..\..\src\LogPlayer\Unit\Commands\ParserCommand6B.pas',
  ParserCommand80 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand80.pas',
  ParserCommand81 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand81.pas',
  ParserCommand82 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand82.pas',
  ParserCommand83 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand83.pas',
  ParserCommand85 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand85.pas',
  ParserCommand89 in '..\..\src\LogPlayer\Unit\Commands\ParserCommand89.pas',
  ParserCommand8E in '..\..\src\LogPlayer\Unit\Commands\ParserCommand8E.pas',
  ParserCommandFF61 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF61.pas',
  ParserCommandFF69 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF69.pas',
  ParserCommandFF01 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF01.pas',
  ParserCommandFF67 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF67.pas',
  ParserCommandFF73 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF73.pas',
  ParserCommandFF70 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF70.pas',
  ParserCommandFF71 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF71.pas',
  ParserCommandFF75 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF75.pas',
  ParserCommandFF72 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF72.pas',
  ParserCommandFF74 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF74.pas',
  ParserCommandFF45 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF45.pas',
  ParserCommandFF78 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF78.pas',
  ParserCommandFF76 in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFF76.pas',
  LogParser2 in '..\..\src\LogPlayer\Unit\LogParser2.pas',
  ShtrihProtocol1 in '..\..\src\LogPlayer\Unit\ShtrihProtocol1.pas',
  duLogParser in 'Units\duLogParser.pas',
  ShtrihProtocol2 in '..\..\src\LogPlayer\Unit\ShtrihProtocol2.pas',
  ParserCommandFC in '..\..\src\LogPlayer\Unit\Commands\ParserCommandFC.pas';

{$R *.RES}

begin
  TGUITestRunner.RunTest(RegisteredTests);
end.
